### ISSUE TITLE
wrong code in computeShortestPath

### ISSUE THREAD

**Issue by gapaluec** [mds1/path-planning#2]
below code seems wrong as costMatrix should have a {x,y,z} as input, while currently there is number and therefore below code always returns 1.
`if isinf(gl.costMatrix[CL.rhs[startnode]]):`
[https://github.com/mds1/path-planning/blob/master/all_functions.py#L1153](https://github.com/mds1/path-planning/blob/master/all_functions.py#L1153)

**Comment by mds1** [comment]
That line of code does not always return 1, because if it did the exception on the following line would always be raised.

**Comment by mds1** [comment]
Looks like I forgot to close this one
