### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by HeZhang1994** [mds1/path-planning#3]
Hi mds,

Thanks for your open source code. Recently I have run the main_dstart.py code with startWithEmptyMap set to False. I have met the following error:

Line 116 - hyp[i] = math.sqrt(xdist**2 + ydist**2 + zdist**2)
TypeError: unhashable type: 'numpy.ndarray' 

I am not sure why this problem happens because this part of codes is similar with main_hdstar.py

Thank you very much!
He

**Comment by mds1** [comment]
Sorry for the late response. Have you figured out the cause of this yet? If not, let me know how to reproduce the issue and I should be able to take a look at this within the next few days

**Comment by HeZhang1994** [comment]
Thanks for you reply. I did not change the code. I guess that might caused because the function.py files are updated but the main_dstar.py was not. I have finished my project so that is not my problem now. If you want to reproduce this problem, you can download the current version and set startWithEmptyMap to False and run it again.

**Comment by mds1** [comment]
Hm, interesting. Unfortunately I currently don't have time to look at it, but I'll leave this issue open for now in case you or anyone else wants to take a shot at fixing this
